### ISSUE TITLE
unix timestamp format support

### ISSUE THREAD

**Issue by SilentCicero** [taylorhakes/fecha#12]
I may have missed it, but is there a way to format("x") or format("unix") to return the date as a unix timestamp?

**Comment by taylorhakes** [comment]
Are you asking for it to return the number of milliseconds since epoch as a number or string?

To create a unix timestamp:

If you need to parse the date from a string:
```js
var myDate = fecha.parse('2012-11-01', 'YYYY-MM-DD');
```
To get the timestamp in milliseconds from `myDate`
```js
var timestamp = myDate.getTime();
```

**Comment by SilentCicero** [comment]
@taylorhakes here is my PR with the features: https://github.com/taylorhakes/fecha/pull/13

These are critical formatting methods for me and most apps I build.

It may add a bit of extra weight, but I think it's totally worth it.

**Comment by taylorhakes** [comment]
Closing because #13 was closed as well
