### ISSUE TITLE
Literal support in formatting mask

### ISSUE THREAD

**Issue by antivanov** [taylorhakes/fecha#18]
moment.js allows to use literals in formatting masks, it would be nice to have a similar feature in fecha.

Example:

```javascript
fecha.format(new Date(2001, 2, 5, 6, 7, 2, 5), '[on] MM-DD-YYYY [at] HH:mm');
// 'on 03-05-2001 at 06:07'
```

PR that implements the feature https://github.com/taylorhakes/fecha/pull/17

**Comment by taylorhakes** [comment]
Complete in #17. Thanks @antivanov.

**Comment by antivanov** [comment]
Thanks for reviewing the changes and merging the PR
