### ISSUE TITLE
Should .parse() return `false`?

### ISSUE THREAD

**Issue by Caneco** [taylorhakes/fecha#2]
Hello!
I was trying to make the following instruction and got the following output.
```
fecha.parse('2015-02-29')
// Sun Mar 01 2015 00:00:00 GMT+0000 (WET)
```
Souldn't return `false` instead of the next day?

**Comment by taylorhakes** [comment]
Unfortunately, that is the correct behavior. See this behavior https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#ECMAScript_5_ISO-8601_format_support

fecha falls back native Date.parse if you don't specify a format. You found the very strange behavior with ISO date formats. With ISO date formats Date.parse assumes GMT time and then converts to local time, which causes the weird result. Luckily in ES6 the behavior is different.

I am going to deprecate and add a warning if a format is not specified. In the next major version I will throw a hard error if a format is not specified. It should limit the confusion you experienced.
