### ISSUE TITLE
YYYYMMDD leads into a complete JS-crash

### ISSUE THREAD

**Issue by williamrijksen** [taylorhakes/fecha#20]
When i don't use the separators between the tokens, it will lead on NodeJS and Chrome into an crash. Please fix or report this issue.

**Comment by taylorhakes** [comment]
@williamrijksen If you could give more details about your issue it would be very helpful. What function are you using (parse or format)? What values are you passing to the function?

When filling out an issue (on any code base) you should show some example code reproducing the issue. It's really difficult to know what is going on from a general error. I hope this doesn't come off as harsh. I really want to fix your issue.

Anyways, I still dug around and tried to find any issues with YYYYMMDD. I added 2 tests to the test suite. One for `fecha.parse` and one for `fecha.parse` with YYYYMMDD. They both pass, but maybe I am not using the right value?

https://github.com/taylorhakes/fecha/commit/dd4b3f4809e814d5e5f9d77a230155d814dc79ee#diff-1dd241c4cd3fd1dd89c570cee98b79ddR21

**Comment by williamrijksen** [comment]
Hello @taylorhakes,

I tested it with the following format:
`fecha.parse('YYYYMMDD', new Date())` on node 6.3.0. Client side it was compiled by babel.

`testParse('YYYYMMDD', '2000-01-01', 'YYYYMMDD', new Date(2000, 0, 1))` doesn't lead into some troubles. I cannot reproduce the problem with your test-suite. Maybe the transpile with babel is the reason of this problem.

**Comment by taylorhakes** [comment]
It looks like you are using `fecha.parse` incorrectly. The arguments are
```js
fecha.parse('<Date String>', '<Date Format>');
```

Are you trying to parse or format?

Please take a look at the readme for the correct way to use `fecha.parse` and `fecha.format`.
https://github.com/taylorhakes/fecha#use-it

**Comment by taylorhakes** [comment]
I am going to close until I get more information.
