### ISSUE TITLE
Conditional params / i.e. year

### ISSUE THREAD

**Issue by petr001** [taylorhakes/fecha#23]
Hi,

is there a way to display year part of the date only when the year is not the current year?

example:
Jan 27
but: Dec 31, 2016

**Comment by taylorhakes** [comment]
There aren't conditionals in the formatter. You can do that yourself.

```js
myDate.getFullYear() === (new Date()).getFullYear() ? fecha.format(myDate, 'MMM DD') : fecha.format(myDate, 'MMM DD, YYYY')
```
