### ISSUE TITLE
Literals not working in minified version

### ISSUE THREAD

**Issue by grafxdesign** [taylorhakes/fecha#27]
Really weird but it stripped out all reference to the literals (eg: 'D MMM YYYY [at] h:mma') so that it was outputting [pmt] or [amt] using the 'a' as a token... I took the fecha.js file over to an online minifyer and it worked fine... Can you guys please correct this and push the working 'official' min.js file to git.

Cheers!
Richard     :o)

**Comment by taylorhakes** [comment]
I updated the minified file. Please let me know if it works
