### ISSUE TITLE
Does fecha.spec.js need to be hosted on cdnjs?

### ISSUE THREAD

**Issue by maruilian11** [taylorhakes/fecha#33]
Hi, I'm from [cdnjs](https://github.com/cdnjs/cdnjs), we host `js`, `css` and `img` lib for browser usage. Recently we want to host your popular lib on https://cdnjs.com, just want to confirm that if we also need to host `fetch.spec.js` because I saw them in some old versions, but unminfied.
Thank you!

https://github.com/cdnjs/cdnjs/pull/11044

**Comment by taylorhakes** [comment]
fecha.spec.js is not necessary. It is only a test file

**Comment by maruilian11** [comment]
thank you!
