### ISSUE TITLE
How to get time from now like momentjs

### ISSUE THREAD

**Issue by kevinjon27** [taylorhakes/fecha#38]
Can fecha do `moment([2007, 0, 29]).fromNow(); // 4 years ago`?
https://momentjs.com/docs/#/displaying/fromnow/

Thanks

**Comment by taylorhakes** [comment]
Unfortunately, no. fecha is only meant for date parsing and formatting, not date durations.

https://github.com/taylorhakes/fecha#fecha-vs-moment
