### ISSUE TITLE
Typescript type definitons are missing from npm package

### ISSUE THREAD

**Issue by madakk** [taylorhakes/fecha#50]
Looks like this has been previously fixed in #39, but broken as of the 3.0.0 release.

**Comment by ecwyne** [comment]
Looks like changes haven't been published to npm since #48

**Comment by balloob** [comment]
3.0.0 has been released and it did not include types

https://unpkg.com/fecha@3.0.0/

**Comment by taylorhakes** [comment]
Thanks for the report. Sorry about the broken npm publish. This is fixed in https://github.com/taylorhakes/fecha/releases/tag/3.0.2
