### ISSUE TITLE
fecha.parse gives me a wrong value.

### ISSUE THREAD

**Issue by micooz** [taylorhakes/fecha#6]
see [snippet](https://github.com/taylorhakes/fecha/blob/master/fecha.js#L203):

    fecha.parse = function (dateStr, format) {
		var time, isValid, dateInfo, today, date, info, index;

		if (!format) {
			time = Date.parse(dateStr.replace(/\-/g, '/'));
			if (!isNaN(time)) {
				return new Date(time);
			} else {
				return false;
			}

		} else {

I have tried the following code on both Chrome and Safari:

    Date.parse("2015-07-18T07:53:14.000Z")
    // 1437205994000
    Date.parse("2015/07/18T07:53:14.000Z")
    // NaN

As you can see, after replace '-' to '/', `Date.parse` cannot parse the date string correctly, then the function gives me 'false'.

The javascript document says:

    Unrecognizable strings or dates containing illegal element values in ISO formatted strings shall cause Date.parse() to return NaN.

Obviously, the `"2015-07-18T07:53:14.000Z"` is legal while `"2015/07/18T07:53:14.000Z"` is illegal.

I don't know why you must change - to /.

**Comment by taylorhakes** [comment]
Thanks for reporting this issue. The reason to switch `-` to `/` was to fix this issue in Firefox.

```
new Date('12-12-2015')
Invalid Date
new Date('12/12/2015')
Date 2015-12-12T05:00:00.000Z
```

If you want to use the built in parse, just use Date.parse. There is not need to use this library. The library is meant for custom date formats. If you are using custom date formats, you should use the format parameter. I will be removing the fallback to Date.parse in the next version.

**Comment by taylorhakes** [comment]
I have updated the version to 1.0.0 and removed the fallback to Date.parse. Please let me know if you see any other issues.

**Comment by micooz** [comment]
I found that I made a mistake on the choice of `fecha.format` and `fecha.parse` after you point out what I should use. I use `fecha.format('2015-07-18T07:53:14.000Z', 'MM/DD HH:mm')` which goes wrong. 

It works fine for me after I switch to use `fecha.parse(...)`, the old version as well.

Anyway, thanks for your awesome library.
