### ISSUE TITLE
Feature request: Support microseconds in timestamp format

### ISSUE THREAD

**Issue by omeraha** [taylorhakes/fecha#61]
Winston@3, AWS Linux instance, Javascript

**What's the feature?**
Add microseconds precision to the timestamp format. something like:
timestamp({ format: 'YYYY-MM-DD HH:mm:ss.<microseconds>' })

**What problem is the feature intended to solve?**
My use case is logging (I'm using Winston which in turn is using fecha under the hood for timestamp formatting). Log aggregation of logs created by many instances of different microservices requires a precision level higher than milliseconds in order to better sort the logs based on their timestamp.

**Is the absence of this feature blocking you or your team? If so, how?**
Not a blocker, but a very desirable feature.

**Is this feature similar to an existing feature in another tool?**
No that I know of.

**Is this a feature you're prepared to implement, with support from us?**
I'd be willing to look into it.

**Comment by taylorhakes** [comment]
I don’t think the Javascript Date object supports microseconds. This library just formats Date objects. Do you know of a way to make it work?

**Comment by omeraha** [comment]
AFAIK, date support up to milliseconds only. Looking at the code, I saw that it is entirely based on the date object, so I guess you can close this feature request.
Thanks anyway!

**Comment by taylorhakes** [comment]
No problem. If this becomes possible in the future, we can reopen.
