### ISSUE TITLE
Allow extending formatting tokens

### ISSUE THREAD

**Issue by alirezamirian** [taylorhakes/fecha#66]
It would be great if formatting tokens can be extensible. For my use case, I want a token for showing year, only if it's not equal to the current year. Other tokens can be relative time (e.g. 3 minutes ago). I don't know if the implementation allows such extensibility but it would be nice to support such feature.

**Comment by taylorhakes** [comment]
@alirezamirian Sorry for the delay. I don't have a good idea of how to do that currently internal to fecha. Unfortunately the only way I know is by changing for format dynamically.

```js
var date = new Date(2015, 10, 20)
fecha.format(date, date.getFullYear() === (new Date()).getFullYear() 'dddd MMMM Do' : 'dddd MMMM Do, YYYY');
```

**Comment by alirezamirian** [comment]
I don't know the internals of fetcha and how the parsing is done but I was thinking maybe the formatting tokens can be extensible in via an API for adding tokens and a function that  returns something. Something like this:
```
fetcha.addToken('smartYear', (date) => ...)
// and then:
fetcha.format(date, 'smartYeat MMMM Do')
```

**Comment by taylorhakes** [comment]
Thanks for explaining. That clears it up a lot.

I see the value of the request, but it will add code and this is the first time it's been requested, so I am hesitant to add it. The goal of this library is meant to be compact, but not feature complete. I will leave this open for a bit and see if others have similar requests.

**Comment by alirezamirian** [comment]
@taylorhakes That makes sense. Thanks.

**Comment by taylorhakes** [comment]
@alirezamirian I haven't receive any other requests for this feature. I am going to close for now. We can reopen in the future if anything changes. Thanks for the suggestion.
