### ISSUE TITLE
Timezone here in Brazil is wrong(correct is -3)

### ISSUE THREAD

**Issue by ValchanOficial** [taylorhakes/fecha#67]
```
const fecha = require('fecha');
console.log(fecha.format(new Date(), 'hh:mm'));

```
Example:
Time now: 05:00 - **right**
fecha.format: 06:00 - **wrong**

Daylight Saving Time has been permanently abolished in Brazil, according to the Senate bulletin of April 25, 2019.

**Comment by fer22f** [comment]
This is not an issue with fecha. Fecha just interprets the date given by `new Date()`. If your `new Date()` has timezone of UTC-02, your system configuration is wrong.

**Comment by ValchanOficial** [comment]
Thanks!!
