### ISSUE TITLE
Add info how to import library into the readme file

### ISSUE THREAD

**Issue by eugene-ilyin** [taylorhakes/fecha#69]
Hello

Thank you for this lightweight library, I really like it.
I found that there is no info on how to import it.
It's quite obvious for an experienced developer, but let's make it simple for newbies also.

I've prepared a simple MR, could you check it? If you will approve, please don't forget to update it on the page of the project for NPM,  because most of the people open the page of the project there.

MR: https://github.com/taylorhakes/fecha/pull/68

**Comment by taylorhakes** [comment]
Thank you for the issue and the PR. I have addressed this issue in version 4.0 beta here. Please let me know if anything is missing.

https://github.com/taylorhakes/fecha/pull/72
