### ISSUE TITLE
Add Z formatting token

### ISSUE THREAD

**Issue by fer22f** [taylorhakes/fecha#75]
Currently `fecha` supports the `ZZ` formatting token, but it would be nice if we also had `Z` [which is defined in moment](https://momentjs.com/docs/#/displaying/format/):

|Token|Output|
|----|----|
| Z | -07:00 -06:00 ... +06:00 +07:00|
| ZZ | -0700 -0600 ... +0600 +0700|

I came across this issue because js-joda currently doesn't parse it without the colon (https://github.com/js-joda/js-joda/issues/377).

EDIT: RFC3339 requires the colon, so yea, we do need this.

**Comment by taylorhakes** [comment]
@fer22f Thank you for creating the issue. I have not received this request before, but I am happy to accept a PR adding it. If you have the time to create a PR, I would be happy to review it and get it added.
