### ISSUE TITLE
isoDateTime and isoDate is in readme but not release

### ISSUE THREAD

**Issue by antonovicha** [taylorhakes/fecha#79]
Readme says that one can use `isoDateTime` and `isoDate` format.

https://github.com/taylorhakes/fecha/commit/b3eb2093680c24325f8c9deb11fe7dd1a810a6a0 commit adds support of it but latest released version (4.1.0) does not have them.

**Comment by taylorhakes** [comment]
Thank you for the report. 4.2.0 has been released now.
