### ISSUE TITLE
No map file in npm version

### ISSUE THREAD

**Issue by troy351** [taylorhakes/fecha#83]
It seems `lib/fecha.js.map` and `lib/fecha.umd.js.map` were not inside node_modules.
But at the end of file `lib/fecha.js` did linked to the map file.
https://github.com/taylorhakes/fecha/blob/91680e4db1415fea33eac878cfd889c80a7b55c7/lib/fecha.js#L386
This makes error when I using [vite](https://github.com/vitejs/vite)
![image](https://user-images.githubusercontent.com/8372385/95846766-66ff9b80-0d7e-11eb-8697-94fca3182a71.png)

**Comment by taylorhakes** [comment]
Deployed version 4.2.1
