### ISSUE TITLE
parse("2022-03-13T02:00:00Z","YYYY-MM-DDTHH:mm:ssZ") fails when it should not

### ISSUE THREAD

**Issue by enimapod** [taylorhakes/fecha#94]
hi
parse("2022-03-13T02:00:00Z","YYYY-MM-DDTHH:mm:ssZ") returns null, but, as far as I can tell, the date is valid.

**Comment by taylorhakes** [comment]
Daylight savings time occurred at that time, so that is not a valid time. It went from 01:59:59 to 03:00:00 on that date in the US.

**Comment by enimapod** [comment]
Thank you for a quick reply. Since fecha has knowledge of dst, and when it happens, can it handle the conversion by adding or removing a sec, perhaps via a flag? it is too much to ask a client to have to figure this out and change all their inputs.

**Comment by taylorhakes** [comment]
I fixed this in version 4.2.3. Thanks for reporting the bug

**Comment by enimapod** [comment]
Thank you for a rapid fix.
